/**
 * Standalone MCP server entry point.
 *
 * Run with:  node dist/standalone.js
 *
 * This process owns the stdio transport that MCP clients (e.g. VS Code Copilot
 * agent mode) connect to.  When review_generated_ui is called it writes a
 * pending session file to the OS temp directory and polls for the result,
 * which the VS Code extension writes back once the user submits the review.
 */
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { handleReviewRequest, ensureBridgeDirs } from "./bridge/fileBridge.js";
import type { ReviewGeneratedUiInput } from "./types.js";

ensureBridgeDirs();

const server = new Server(
  { name: "review-generated-ui", version: "0.1.0" },
  { capabilities: { tools: {} } },
);

const toolDefinition = {
  name: "review_generated_ui",
  description:
    "Sends agent-generated HTML to a human reviewer in VS Code. " +
    "Waits for the human to approve or request changes, then returns " +
    "the reviewed HTML and the approval status.",
  inputSchema: {
    type: "object" as const,
    properties: {
      html: {
        type: "string",
        description: "The HTML content generated by the agent to be reviewed.",
      },
      instructions: {
        type: "string",
        description: "Optional context or review instructions shown to the reviewer.",
      },
      title: {
        type: "string",
        description: "Optional display title for this review session.",
      },
    },
    required: ["html"],
  },
};

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [toolDefinition],
}));

server.setRequestHandler(
  CallToolRequestSchema,
  async (request: { params: { name: string; arguments?: Record<string, unknown> } }) => {
    const { name, arguments: args } = request.params;

    if (name !== "review_generated_ui") {
      return {
        content: [{ type: "text" as const, text: `Unknown tool: ${name}` }],
        isError: true,
      };
    }

    try {
      const input = (args ?? {}) as unknown as ReviewGeneratedUiInput;
      const result = await handleReviewRequest(input);
      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify({ status: result.status, reviewedHtml: result.reviewedHtml }),
          },
        ],
      };
    } catch (err) {
      return {
        content: [
          {
            type: "text" as const,
            text: `Review cancelled: ${err instanceof Error ? err.message : String(err)}`,
          },
        ],
        isError: true,
      };
    }
  },
);

const transport = new StdioServerTransport();
server.connect(transport).catch((err) => {
  process.stderr.write(`Failed to start MCP server: ${err}\n`);
  process.exit(1);
});
