import { randomUUID } from "crypto";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import { ReviewGeneratedUiInput, ReviewResult, ReviewSession } from "../types";
import { sessionStore } from "../sessions/store";
import { sanitizeHtml, validateReviewHtml } from "../html/sanitize";

export interface McpToolHandler {
  definition: Tool;
  handler: (args: Record<string, unknown>) => Promise<{
    content: Array<{ type: "text"; text: string }>;
  }>;
}

export function createReviewGeneratedUiTool(
  onNewSession: (session: ReviewSession) => void,
): McpToolHandler {
  const definition: Tool = {
    name: "review_generated_ui",
    description:
      "Sends agent-generated HTML to a human reviewer. Waits for the human to " +
      "approve or request changes, then returns the reviewed HTML and status.",
    inputSchema: {
      type: "object",
      properties: {
        html: {
          type: "string",
          description: "The HTML content generated by the agent to be reviewed.",
        },
        instructions: {
          type: "string",
          description:
            "Optional instructions or context to show the reviewer alongside the UI.",
        },
        title: {
          type: "string",
          description: "Optional display title for this review session.",
        },
      },
      required: ["html"],
    },
  };

  const handler = async (
    args: Record<string, unknown>,
  ): Promise<{ content: Array<{ type: "text"; text: string }> }> => {
    const input = args as unknown as ReviewGeneratedUiInput;

    validateReviewHtml(input.html);
    const sanitized = sanitizeHtml(input.html);
    const sessionId = randomUUID();
    const title = input.title ?? "Untitled Review";

    const session = sessionStore.create(sessionId, title, sanitized);
    if (input.instructions) session.instructions = input.instructions;

    // Default timeout: 10 minutes. The reviewer must submit before then.
    const TIMEOUT_MS = 10 * 60 * 1000;

    const result = await new Promise<ReviewResult>((resolve, reject) => {
      sessionStore.setReject(sessionId, reject);
      session.resolve = (r: ReviewResult) => resolve(r);
      onNewSession(session);

      setTimeout(() => {
        sessionStore.cancel(sessionId, 'Review timed out – no response within 10 minutes');
      }, TIMEOUT_MS);
    });

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({
            status: result.status,
            reviewedHtml: result.reviewedHtml,
          }),
        },
      ],
    };
  };

  const safeHandler = async (
    args: Record<string, unknown>,
  ): Promise<{ content: Array<{ type: "text"; text: string }>; isError?: boolean }> => {
    try {
      return await handler(args);
    } catch (err) {
      return {
        content: [{ type: "text", text: `Review cancelled: ${String(err instanceof Error ? err.message : err)}` }],
        isError: true,
      };
    }
  };

  return { definition, handler: safeHandler };
}
